# Generated by Django 3.2.9 on 2021-11-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
