# Generated by Django 3.2.9 on 2021-11-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0003_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_count',
            new_name='walletcount',
        ),
    ]
