# Generated by Django 3.2.9 on 2021-11-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0004_rename_wallet_count_wallet_walletcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='walletcount',
            field=models.IntegerField(default=0),
        ),
    ]
