# Generated by Django 3.2.9 on 2021-11-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
