# Generated by Django 3.2.9 on 2021-11-19 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0011_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transactiondate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
