# Generated by Django 3.2.9 on 2021-11-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0012_wallet_transactiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transactiondate',
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('transactiondate', models.DateTimeField(auto_now_add=True)),
                ('wallets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecopp.wallet')),
            ],
        ),
    ]
