# Generated by Django 3.2.9 on 2021-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0014_alter_wallethistory_transactiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='transactiondate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
