# Generated by Django 3.2.9 on 2021-11-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0016_alter_wallethistory_transactiondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleHistoryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('totalsold', models.IntegerField()),
            ],
        ),
    ]
