# Generated by Django 3.2.9 on 2021-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0019_alter_order_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchasedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
