# Generated by Django 3.2.9 on 2021-11-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0020_alter_order_purchasedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleHistoryDate',
        ),
    ]
