# Generated by Django 3.2.9 on 2021-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopp', '0022_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
